Repository emodyz/MultigamingPanel, pull requests merged in 2021-02, with the labels that each got.

#63 Feature/62 | Better handling of client-side authorisations
  app/Http/Controllers/SettingsController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Http/Requests/Settings/EditVoiceSettingsRequest.php
  app/Models/User.php
  composer.json
  composer.lock
  config/cerberus.php
  package.json
  resources/css/app.css
  resources/js/Jetstream/Button.vue
  resources/js/Jetstream/FormSection.vue
  resources/js/Jetstream/Label.vue
  resources/js/Jetstream/NavLink.vue
  resources/js/Jetstream/SecondaryButton.vue
  resources/js/Jetstream/SectionBorder.vue
  resources/js/Jetstream/SectionTitle.vue
  resources/js/Jetstream/Welcome.vue
  resources/js/Layouts/AppLayout.vue
  resources/js/Mixins/Cerberus.ts
  resources/js/Mixins/Helpers.ts
  resources/js/Pages/ModPacks/Components/CreateModPackModal.vue
  resources/js/Pages/Users/Edit.vue
  resources/js/Pages/Users/EditUserProfileForm.vue
  resources/js/Shared/DataTable/Components/Dialogs/DeleteArticle.vue
  resources/js/Shared/DataTable/DataTable.vue
  resources/js/Shared/DataTable/Types/User.d.ts
  resources/js/Shared/Forms/ToggleSwitch.vue
  resources/js/Shared/Helpers/doesNotExist.ts
  resources/js/Shared/Services/Cerberus/WildcardAuthorization.ts
  resources/js/Shared/Services/Cerberus/cerberus.service.ts
  resources/js/app.ts
  resources/views/app.blade.php
  routes/web.php
  tailwind.config.js
  yarn.lock
Labels: To Do (Fastly), UI, dependencies, enhancement, php

#71 Feature #70 - Support 2FA for api
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  tests/Feature/Auth/LoginTest.php
Labels: bug

#74 Feature #67 | Dashboard Stats
  app/Http/Controllers/Dashboard/Contracts/DashboardStats.php
  app/Http/Controllers/Dashboard/DashboardController.php
  app/Http/Controllers/Dashboard/ServerStats.php
  app/Http/Controllers/Dashboard/StatsController.php
  app/Http/Controllers/Dashboard/UsersStats.php
  app/Http/Kernel.php
  app/Models/Server.php
  composer.json
  composer.lock
  config/cerberus.php
  config/cors.php
  database/factories/ServerStatusFactory.php
  database/factories/UserFactory.php
  database/seeders/ServerSeeder.php
  database/seeders/UserSeeder.php
  package.json
  resources/js/Pages/Articles/Index.vue
  resources/js/Pages/Dashboard.vue
  resources/js/Pages/Dashboard/Components/ServerChart.vue
  resources/js/Pages/Dashboard/Components/UsersChart.vue
  resources/js/Pages/Dashboard/Dashboard.vue
  resources/js/Pages/ModPacks/Index.vue
  resources/js/Pages/Servers/Index.vue
  resources/js/Shared/DataTable/DataTable.vue
  resources/js/Shared/Forms/ToggleSwitch.vue
  resources/js/bootstrap.ts
  routes/api.php
  routes/web.php
  storage/debugbar/.gitignore
  tests/Feature/StatsControllerTest.php
  tests/TestCase.php
  yarn.lock
Labels: enhancement

#76 Feature #75 | theme switcher
  resources/js/Layouts/AppLayout.vue
  resources/js/Layouts/ThemeSwitch.vue
  resources/js/Shared/Pagination/Pagination.vue
  resources/js/Shared/Svgs/Moon.vue
  resources/js/Shared/Svgs/Sun.vue
Labels: enhancement
